# Generated by Django 5.1.15 on 2026-07-06 22:02

import common.utils
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=300)),
                ('legal_name', models.CharField(blank=True, max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to=common.utils.upload_to_path)),
                ('address', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=150)),
                ('country', models.CharField(default='Pakistan', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('tax_id', models.CharField(blank=True, help_text='NTN / Tax registration number', max_length=100)),
                ('registration_number', models.CharField(blank=True, max_length=100)),
                ('default_currency', models.CharField(default='PKR', max_length=3)),
                ('is_primary', models.BooleanField(default=False, help_text='The primary company shown on documents.')),
            ],
            options={
                'verbose_name_plural': 'companies',
                'ordering': ['-is_primary', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NumberingScheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.CharField(choices=[('asset', 'Asset / Device'), ('supplier', 'Supplier'), ('client', 'Client'), ('purchase_order', 'Purchase Order'), ('invoice', 'Invoice'), ('work_order', 'Work Order'), ('project', 'Project'), ('ticket', 'Ticket'), ('goods_receipt', 'Goods Receipt'), ('issuance', 'Inventory Issuance'), ('inventory_item', 'Inventory Item (SKU)')], max_length=30, unique=True)),
                ('prefix', models.CharField(max_length=12)),
                ('separator', models.CharField(default='-', max_length=3)),
                ('include_year', models.BooleanField(default=True)),
                ('padding', models.PositiveSmallIntegerField(default=5, help_text='Zero-pad width for the sequence number')),
                ('next_number', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['entity'],
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('days', models.PositiveSmallIntegerField(default=0, help_text='Net days until payment is due')),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'payment terms',
                'ordering': ['days', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TermsTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('work_order', 'Work Order'), ('safety', 'Safety Instructions'), ('general', 'General')], default='general', max_length=20)),
                ('body', models.TextField()),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='WarrantyPeriodPreset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(help_text="e.g. '1 Year', '18 Months'", max_length=100, unique=True)),
                ('months', models.PositiveSmallIntegerField(help_text='Duration in months')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['months'],
            },
        ),
    ]
