# Generated by Django 5.1.15 on 2026-08-17 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0002_seed_numbering_schemes'),
    ]

    operations = [
        migrations.CreateModel(
            name='EscalationPolicy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('trigger', models.CharField(choices=[('assignment_sla', 'Unassigned beyond window'), ('response_sla', 'No response within SLA'), ('due_date', 'Past due date')], max_length=20, unique=True)),
                ('hours', models.PositiveIntegerField(blank=True, help_text='Window in hours (assignment trigger). Blank = response SLA uses per-priority windows; due date fires the day after.', null=True)),
                ('escalate_to_role', models.CharField(default='group_head', help_text='Role that receives the escalation (accounts.User.Role value)', max_length=20)),
                ('also_notify_role', models.CharField(blank=True, default='ops_manager', help_text='Additional role notified alongside (blank = none)', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'escalation policies',
                'ordering': ['trigger'],
            },
        ),
    ]
