# Generated by Django 5.1.15 on 2026-08-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0006_seed_quotation_numbering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='escalationpolicy',
            options={'ordering': ['scope', 'trigger', 'stage'], 'verbose_name_plural': 'escalation policies'},
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='scope',
            field=models.CharField(choices=[('ticket', 'Ticket'), ('installation', 'Installation')], default='ticket', max_length=20),
        ),
        migrations.AddField(
            model_name='escalationpolicy',
            name='stage',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='hours',
            field=models.PositiveIntegerField(blank=True, help_text='Offset in hours from the trigger anchor for this stage (stage hours are absolute from the anchor). Blank = 0 (assignment trigger falls back to 24).', null=True),
        ),
        migrations.AlterField(
            model_name='escalationpolicy',
            name='trigger',
            field=models.CharField(choices=[('assignment_sla', 'Unassigned beyond window'), ('response_sla', 'No response within SLA'), ('due_date', 'Past due date')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='escalationpolicy',
            unique_together={('scope', 'trigger', 'stage')},
        ),
    ]
