# Generated by Django 5.1.15 on 2026-09-01 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setup', '0008_seed_stage_policies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='numberingscheme',
            name='entity',
            field=models.CharField(choices=[('asset', 'Asset / Device'), ('supplier', 'Supplier'), ('client', 'Client'), ('purchase_order', 'Purchase Order'), ('quotation', 'Quotation'), ('invoice', 'Invoice'), ('work_order', 'Work Order'), ('project', 'Project'), ('ticket', 'Ticket'), ('goods_receipt', 'Goods Receipt'), ('issuance', 'Inventory Issuance'), ('inventory_item', 'Inventory Item (SKU)'), ('inventory_unit', 'Inventory Unit (Unique Item)')], max_length=30, unique=True),
        ),
    ]
