# Generated by Django 5.1.15 on 2026-09-16 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_materialtype_options_assetcomponent_unit_and_more'),
        ('teams', '0011_project_sites_alter_project_phase_and_more'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='assets.device'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='teams.project'),
        ),
    ]
