# Generated by Django 5.1.15 on 2026-09-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0024_vendor_asset_procurement_and_step_work_orders'),
        ('workorders', '0002_workorder_device_workorder_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='production_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='assets.productionstep'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_type',
            field=models.CharField(choices=[('supply', 'Supply / Purchase'), ('installation', 'Installation'), ('supply_install', 'Supply & Installation'), ('production', 'Production Step')], default='supply_install', max_length=20),
        ),
    ]
