# Generated by Django 5.1.15 on 2026-09-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_productionstep_work_order_requested_at'),
        ('workorders', '0003_vendor_asset_procurement_and_step_work_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='production_step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_items', to='assets.productionstep'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='order_type',
            field=models.CharField(choices=[('services', 'Services'), ('supply', 'Supply / Purchase'), ('installation', 'Installation'), ('supply_install', 'Supply & Installation'), ('production', 'Production Step')], default='services', max_length=20),
        ),
    ]
