# Generated by Django 5.1.15 on 2026-09-19 19:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_services_and_line_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_work_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorder',
            name='inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='inspection_result',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rework', 'Sent back for rework')], max_length=10),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('issued', 'Issued to Supplier'), ('in_progress', 'In Progress'), ('partially_delivered', 'Partially Delivered'), ('delivered', 'Delivered — awaiting inspection'), ('completed', 'Completed — inspected'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
    ]
