# Generated by Django 5.1.15 on 2026-09-20 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_the_order_down_to_its_lines(apps, schema_editor):
    """Orders delivered or completed before lines had their own state.

    Everything on a completed order was delivered and accepted, and everything
    on a delivered one is waiting to be looked at — otherwise those lines would
    read as still being with the vendor.
    """
    WorkOrder = apps.get_model("workorders", "WorkOrder")
    for order in WorkOrder.objects.filter(
        status__in=("delivered", "partially_delivered", "completed")
    ).prefetch_related("items"):
        when = order.delivered_at or order.updated_at
        for line in order.items.all():
            fields = []
            if line.delivered_at is None:
                line.delivered_at = when
                fields.append("delivered_at")
            if order.status == "completed" and not line.inspection_result:
                line.inspection_result = "accepted"
                line.inspected_at = order.inspected_at or when
                line.inspected_by_id = order.inspected_by_id
                line.inspection_notes = order.inspection_notes
                fields += ["inspection_result", "inspected_at", "inspected_by", "inspection_notes"]
            if fields:
                line.save(update_fields=fields)


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0005_work_receiving'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workorderitem',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_order_lines_inspected', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workorderitem',
            name='inspection_result',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted'), ('rework', 'Sent back for rework')], max_length=10),
        ),
        migrations.RunPython(carry_the_order_down_to_its_lines, migrations.RunPython.noop),
    ]
