# Generated by Django 5.1.15 on 2026-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0007_workorderitem_reference_label_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='payment_terms_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
