# Generated by Django 5.1.15 on 2026-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('ops_manager', 'Operations Manager'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('finance', 'Finance'), ('warehouse', 'Warehouse Staff'), ('client_viewer', 'Client Viewer')], default='technician', max_length=20),
        ),
    ]
