# Generated by Django 5.1.15 on 2026-07-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('ops_manager', 'Operations Manager'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('warehouse', 'Warehouse Staff'), ('client_viewer', 'Client Viewer')], default='technician', max_length=20),
        ),
    ]
