# Generated by Django 5.1.15 on 2026-08-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('group_head', 'Group Head'), ('ops_manager', 'Operations Head'), ('marketing_head', 'Marketing Head'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('warehouse', 'Warehouse Staff'), ('client_viewer', 'Client Viewer')], default='technician', max_length=20),
        ),
    ]
