# Generated by Django 5.1.15 on 2026-08-31 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_job_title_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cnic',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator('^\\d{5}-\\d{7}-\\d$', 'CNIC must be in #####-#######-# format')]),
        ),
        migrations.AddField(
            model_name='user',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='leaving_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
