# Generated by Django 5.1.15 on 2026-08-31 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_cnic_user_employee_id_user_join_date_and_more'),
        ('suppliers', '0003_seed_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='suppliers.supplier'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('group_head', 'Group Head'), ('ops_manager', 'Operations Head'), ('marketing_head', 'Marketing Head'), ('supervisor', 'Supervisor'), ('technician', 'Technician'), ('marketing', 'Marketing'), ('finance', 'Finance'), ('warehouse', 'Warehouse Staff'), ('client_viewer', 'Client Viewer'), ('vendor', 'Vendor')], default='technician', max_length=20),
        ),
    ]
