# Generated by Django 5.1.15 on 2026-09-27 20:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_reports_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCapability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('capability', models.CharField(max_length=50)),
                ('allowed', models.BooleanField()),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capabilities_granted', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capability_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user capabilities',
                'ordering': ['capability'],
                'unique_together': {('user', 'capability')},
            },
        ),
    ]
