# Generated by Django 5.1.15 on 2026-09-27 21:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_usercapability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='technician', max_length=50),
        ),
        migrations.CreateModel(
            name='RoleDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('capabilities', models.JSONField(blank=True, default=list)),
                ('is_builtin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_builtin', 'label'],
            },
        ),
    ]
