# Generated by Django 5.1.15 on 2026-09-29 04:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_role_roledefinition'),
        ('clients', '0002_alter_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='client',
            field=models.ForeignKey(blank=True, help_text='For client_viewer logins: the client whose records they may see.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portal_users', to='clients.client'),
        ),
    ]
