# Generated by Django 5.1.15 on 2026-08-31 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_device_source_alter_device_status'),
        ('procurement', '0003_alter_purchaseorder_po_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='asset_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.assettype'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.devicemodel'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='assets.materialtype'),
        ),
    ]
