# Generated by Django 5.1.15 on 2026-08-31 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_purchaseorderitem_asset_type_and_more'),
        ('teams', '0005_projectbomline_bomallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='bom_line',
            field=models.ForeignKey(blank=True, help_text='Project BOM line this item was raised to cover (from-shortage flow)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_items', to='teams.projectbomline'),
        ),
    ]
