# Generated by Django 5.1.15 on 2026-09-04 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryunittype_inventoryunit_unit_type'),
        ('procurement', '0006_purchaseorderitem_inventory_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_items', to='inventory.inventoryitem'),
        ),
    ]
