# Generated by Django 5.1.15 on 2026-09-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_purchaseorderitem_inventory_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='terms',
            field=models.TextField(blank=True),
        ),
    ]
