# Generated by Django 5.1.15 on 2026-09-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_backfill_order_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='supplier_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_charge',
            field=models.BooleanField(default=False),
        ),
    ]
