# Generated by Django 5.1.15 on 2026-10-05 07:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_charges_and_supplier_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='reference_label',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='reference_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variance_decided_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variance_decided_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_variance_decisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variance_decided_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variance_owner',
            field=models.CharField(blank=True, choices=[('project', 'Project Execution'), ('inventory', 'Inventory'), ('operations', 'Operations Head')], max_length=12),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variance_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='variance_status',
            field=models.CharField(choices=[('not_required', 'Within reference'), ('pending', 'Awaiting approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='not_required', max_length=14),
        ),
    ]
