# Generated by Django 5.1.15 on 2026-10-06 11:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0012_alter_purchaseorderitem_variance_decided_by'),
        ('setup', '0016_seed_request_numbering'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='setup.paymentterms'),
        ),
    ]
