# Generated by Django 5.1.15 on 2026-10-06 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_the_journal_says_grn_once'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='payment_terms_note',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
