# Generated by Django 5.1.15 on 2026-10-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_seed_service_categories'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at']},
        ),
    ]
