# Generated by Django 5.1.15 on 2026-04-23 17:58

import common.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0003_device_image_deviceimage'),
        ('sites', '0002_site_state_province_alter_site_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('doc_type', models.CharField(choices=[('report', 'Report'), ('specification', 'Specification'), ('drawing', 'Drawing / Diagram'), ('manual', 'Manual'), ('contract', 'Contract'), ('invoice', 'Invoice'), ('photo', 'Photo'), ('other', 'Other')], default='other', max_length=20)),
                ('file', models.FileField(upload_to=common.utils.upload_to_path)),
                ('file_size', models.PositiveIntegerField(default=0, help_text='Size in bytes')),
                ('description', models.TextField(blank=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='assets.device')),
                ('installation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='sites.deviceinstallation')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
