# Generated by Django 5.1.15 on 2026-07-08 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0002_initial'),
        ('tickets', '0003_alter_ticket_status'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='tickets.ticket'),
        ),
        migrations.AddField(
            model_name='document',
            name='work_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='workorders.workorder'),
        ),
    ]
