# Generated by Django 5.1.15 on 2026-07-09 16:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0003_seed_service_categories'),
        ('tickets', '0004_ticket_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketIssueType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='assigned_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='escalated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='occurrence',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='parts_used',
            field=models.TextField(blank=True, help_text='Parts consumed during rectification'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='response_due_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('blocked', 'Blocked'), ('alignment_pending', 'Alignment Pending'), ('pending_ops_approval', 'Pending Ops Approval'), ('pending_client_approval', 'Pending Client Approval'), ('pending_review', 'Pending Review'), ('approved', 'Resolved (Ops Approved)'), ('rejected', 'Rejected'), ('closed', 'Closed')], default='open', max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketattachment',
            name='attachment_type',
            field=models.CharField(choices=[('general', 'General'), ('fault', 'Fault Evidence'), ('completion', 'Completion Evidence'), ('review', 'Review Attachment')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='ticket',
            name='issue_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketissuetype'),
        ),
    ]
