# Generated by Django 5.1.15 on 2026-07-09 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_seed_issue_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='new_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='old_status',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
