# Generated by Django 5.1.15 on 2026-07-09 19:53

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticketcomment_new_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='image',
            field=models.ImageField(blank=True, help_text='Optional photo attached to the comment', upload_to=common.utils.upload_to_path),
        ),
        migrations.AlterField(
            model_name='ticketcomment',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
