# Generated by Django 5.1.15 on 2026-07-10 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_ticketcomment_image_alter_ticketcomment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='complaint_by',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
