# Generated by Django 5.1.15 on 2026-08-31 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_device_source_alter_device_status'),
        ('tickets', '0012_backfill_closed_at'),
        ('warranties', '0004_vendors_custom_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='charge_to',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('client', 'Client'), ('vendor', 'Vendor')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ticket',
            name='devices',
            field=models.ManyToManyField(blank=True, related_name='linked_tickets', to='assets.device'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='repair_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='warranty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='warranties.warranty'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('replacement', 'Replacement'), ('inspection', 'Inspection'), ('relocation', 'Relocation'), ('warranty_claim', 'Warranty Claim'), ('preventive_maintenance', 'Preventive Maintenance'), ('other', 'Other')], default='other', max_length=30),
        ),
    ]
