# Generated by Django 5.1.15 on 2026-08-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_backfill_ticket_devices'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='escalation_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
