# Generated by Django 5.1.15 on 2026-09-13 18:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryunittype_inventoryunit_unit_type'),
        ('tickets', '0015_ticket_escalation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='inventory_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claims', to='inventory.inventoryunit'),
        ),
    ]
