# Generated by Django 5.1.15 on 2026-09-22 18:58

from django.db import migrations, models


def move_planned_rounds_to_predictive(apps, schema_editor):
    """Tickets filed under the old category keep their meaning.

    Preventive work is a maintenance schedule with its own rounds; a ticket is
    raised against a fault or a warning sign, which is what these were.
    """
    apps.get_model("tickets", "Ticket").objects.filter(
        category="preventive_maintenance"
    ).update(category="predictive_maintenance")


def back_to_preventive(apps, schema_editor):
    apps.get_model("tickets", "Ticket").objects.filter(
        category="predictive_maintenance"
    ).update(category="preventive_maintenance")


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_ticket_inventory_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('replacement', 'Replacement'), ('inspection', 'Inspection'), ('relocation', 'Relocation'), ('warranty_claim', 'Warranty Claim'), ('predictive_maintenance', 'Predictive Maintenance'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.RunPython(move_planned_rounds_to_predictive, back_to_preventive),
    ]
