# Generated by Django 5.1.15 on 2026-09-27 06:22

from django.db import migrations, models


def claims_are_the_work_they_asked_for(apps, schema_editor):
    """A claim was never a kind of work: it was a repair somebody else paid for.

    The cost side is worked out from the asset's cover and kept on the ticket,
    so the category falls back to the work itself.
    """
    apps.get_model("tickets", "Ticket").objects.filter(category="warranty_claim").update(
        category="repair"
    )


def back_to_claims(apps, schema_editor):
    """Nothing to undo: which repairs were once filed as claims is not kept."""


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_predictive_not_preventive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('replacement', 'Replacement'), ('inspection', 'Inspection'), ('relocation', 'Relocation'), ('predictive_maintenance', 'Predictive Maintenance'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.RunPython(claims_are_the_work_they_asked_for, back_to_claims),
    ]
