# Generated by Django 5.1.15 on 2026-10-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold'), ('blocked', 'Blocked'), ('alignment_pending', 'Alignment Pending'), ('pending_ops_approval', 'Pending Ops Approval'), ('pending_client_approval', 'Pending Client Approval'), ('pending_review', 'Pending Review'), ('approved', 'Resolved (Ops Approved)'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=30),
        ),
    ]
