# Generated by Django 5.1.15 on 2026-08-31 05:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_seed_inventory_categories'),
        ('teams', '0005_projectbomline_bomallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuance',
            name='bom_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuances', to='teams.projectbomline'),
        ),
        migrations.AddField(
            model_name='issuance',
            name='issued_to_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_issuances', to='teams.project'),
        ),
    ]
