# Generated by Django 5.1.15 on 2026-08-31 05:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_issuance_bom_line_issuance_issued_to_project'),
        ('procurement', '0005_purchaseorderitem_bom_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipts', to='procurement.purchaseorder'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='inventory.inventoryitem'),
        ),
        migrations.AlterField(
            model_name='goodsreceipt',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField()),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('serial_numbers', models.JSONField(blank=True, default=list)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='inventory.inventoryitem')),
                ('po_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receipt_lines', to='procurement.purchaseorderitem')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='inventory.goodsreceipt')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
