# Generated by Django 5.1.15 on 2026-09-01 18:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_device_source_alter_device_status'),
        ('inventory', '0005_goodsreceipt_purchase_order_alter_goodsreceipt_item_and_more'),
        ('suppliers', '0003_seed_service_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit_code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('serial_number', models.CharField(db_index=True, max_length=200, unique=True)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('in_stock', 'In Stock'), ('reserved', 'Reserved'), ('issued', 'Issued'), ('returned', 'Returned'), ('damaged', 'Damaged'), ('scrapped', 'Scrapped'), ('converted', 'Registered as Asset')], db_index=True, default='in_stock', max_length=15)),
                ('location', models.CharField(choices=[('warehouse', 'Warehouse'), ('in_transit', 'In Transit')], default='warehouse', max_length=15)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('has_warranty', models.BooleanField(default=False)),
                ('warranty_type', models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('extended', 'Extended'), ('supplier', 'Supplier'), ('client', 'Client Warranty')], max_length=20)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_months', models.PositiveSmallIntegerField(blank=True, help_text='Months from start; end date is derived when not given directly', null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_units', to='assets.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='inventory.inventorycategory')),
                ('converted_device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_inventory_unit', to='assets.device')),
                ('goods_receipt_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='inventory.goodsreceiptline')),
                ('material_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory_units', to='assets.materialtype')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_units', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'location'], name='inventory_i_status_bae147_idx'), models.Index(fields=['material_type', 'status'], name='inventory_i_materia_7f81fe_idx')],
            },
        ),
    ]
