# Generated by Django 5.1.15 on 2026-09-01 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_inventoryunit'),
        ('procurement', '0005_purchaseorderitem_bom_line'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='accepted_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='inspected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspected_receipt_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='inspection_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='inspection_status',
            field=models.CharField(choices=[('pending', 'Pending Inspection'), ('passed', 'Passed — Stocked'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='rejected_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='routed_to',
            field=models.CharField(blank=True, choices=[('generic', 'Generic Stock'), ('unique', 'Unique Items')], max_length=10),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='batch_number',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='goods_receipt_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.goodsreceiptline'),
        ),
        migrations.AddIndex(
            model_name='goodsreceiptline',
            index=models.Index(fields=['inspection_status', 'created_at'], name='inventory_g_inspect_84e124_idx'),
        ),
    ]
