# Generated by Django 5.1.15 on 2026-09-01 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_assetcomponent_inventory_item_and_more'),
        ('inventory', '0007_goodsreceiptline_accepted_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryunit',
            name='material_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_units', to='assets.materialtype'),
        ),
    ]
