# Generated by Django 5.1.15 on 2026-09-04 15:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_device_assigned_vendor_contact_and_more'),
        ('inventory', '0008_alter_inventoryunit_material_type'),
        ('suppliers', '0003_seed_service_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUnitType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_code', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('model_name', models.CharField(blank=True, max_length=200)),
                ('specifications', models.JSONField(blank=True, default=dict, help_text='Free-form technical details captured when the item is opened')),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('min_stock_level', models.IntegerField(default=0)),
                ('default_has_warranty', models.BooleanField(default=False)),
                ('default_warranty_type', models.CharField(blank=True, max_length=20)),
                ('default_warranty_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_unit_types', to='assets.brand')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unit_types', to='inventory.inventorycategory')),
                ('material_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_unit_types', to='assets.materialtype')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_unit_types', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='inventoryunit',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='units', to='inventory.inventoryunittype'),
        ),
    ]
