# Generated by Django 5.1.15 on 2026-09-13 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_inventoryunittype_inventoryunit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='storage_location',
            field=models.CharField(blank=True, help_text='Where it is placed, e.g. Rack A3', max_length=200),
        ),
    ]
