# Generated by Django 5.1.15 on 2026-09-14 01:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_assetcomponent_increase_notes_and_more'),
        ('inventory', '0010_inventoryitem_storage_location'),
        ('maintenance', '0007_maintenancerecord_charge_to_and_more'),
        ('teams', '0010_projectcostline_actual_quantity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IssuanceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_number', models.CharField(blank=True, db_index=True, max_length=50, unique=True)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_issued', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('project', 'Project'), ('maintenance', 'Maintenance'), ('other', 'Other')], default='other', max_length=12)),
                ('purpose', models.CharField(blank=True, max_length=300)),
                ('received_by', models.CharField(blank=True, help_text='Who took the material away', max_length=200)),
                ('issued_serials', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Awaiting Issue'), ('partial', 'Partly Issued'), ('fulfilled', 'Issued'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('asset_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issuance_requests', to='assets.assetcomponent')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests_issued', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuance_requests', to='inventory.inventoryitem')),
                ('maintenance_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuance_requests', to='maintenance.maintenanceschedule')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issuance_requests', to='teams.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_requests', to=settings.AUTH_USER_MODEL)),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issuance_requests', to='inventory.inventoryunittype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
