# Generated by Django 5.1.15 on 2026-09-14 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_issuancerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunittype',
            name='is_high_value',
            field=models.BooleanField(default=False, help_text='Include this product in in-hand stock on the dashboard'),
        ),
    ]
