# Generated by Django 5.1.15 on 2026-09-16 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_inventoryunittype_is_high_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceipt',
            name='source',
            field=models.CharField(choices=[('purchase', 'Purchase Order'), ('project_return', 'Returned from Project'), ('maintenance_return', 'Returned from Maintenance')], default='purchase', max_length=20),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='watch_on_dashboard',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryunittype',
            name='unit',
            field=models.CharField(default='piece', max_length=50),
        ),
    ]
