# Generated by Django 5.1.15 on 2026-09-17 17:52

from django.db import migrations, models


def flag_legacy_procurement_requests(apps, schema_editor):
    """Requests raised by earlier Procure decisions were only marked in their purpose text."""
    IssuanceRequest = apps.get_model("inventory", "IssuanceRequest")
    IssuanceRequest.objects.filter(purpose__contains="procurement in progress").update(awaiting_procurement=True)



class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_goodsreceipt_source_inventoryitem_watch_on_dashboard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuancerequest',
            name='awaiting_procurement',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(flag_legacy_procurement_requests, migrations.RunPython.noop),
    ]
