# Generated by Django 5.1.15 on 2026-09-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_close_covered_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuancerequest',
            name='last_issued_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
