# Generated by Django 5.1.15 on 2026-09-19 17:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_issuancerequest_last_issued_at'),
        ('procurement', '0009_backfill_order_dates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(help_text='Reorder quantity')),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('status', models.CharField(choices=[('open', 'Requested'), ('ordered', 'On purchase order'), ('received', 'Received'), ('cancelled', 'Cancelled')], db_index=True, default='open', max_length=12)),
                ('notes', models.TextField(blank=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_requests', to='inventory.inventoryitem')),
                ('purchase_order_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_requests', to='procurement.purchaseorderitem')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_requests', to=settings.AUTH_USER_MODEL)),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reorder_requests', to='inventory.inventoryunittype')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
