# Generated by Django 5.1.15 on 2026-09-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_reorderrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='issuancerequest',
            name='handovers',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
