# Generated by Django 5.1.15 on 2026-09-27 10:33

import django.db.models.deletion
from django.db import migrations, models


def remember_where_the_issued_units_went(apps, schema_editor):
    """Units issued before this was recorded still say where they went.

    The store's own request holds the serials it handed over and the
    requirement they were for, which is exactly the link that was missing.
    """
    IssuanceRequest = apps.get_model("inventory", "IssuanceRequest")
    InventoryUnit = apps.get_model("inventory", "InventoryUnit")
    AssetComponent = apps.get_model("assets", "AssetComponent")

    for request in IssuanceRequest.objects.exclude(asset_component=None).exclude(issued_serials=[]):
        InventoryUnit.objects.filter(
            serial_number__in=request.issued_serials, fitted_to__isnull=True,
        ).update(fitted_to_id=request.asset_component_id)

    # A requirement that named a single unit keeps naming it.
    for component in AssetComponent.objects.exclude(inventory_unit=None):
        InventoryUnit.objects.filter(pk=component.inventory_unit_id, fitted_to__isnull=True).update(
            fitted_to_id=component.pk
        )


def forget(apps, schema_editor):
    apps.get_model("inventory", "InventoryUnit").objects.update(fitted_to=None)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_asset_code_identifies_the_asset'),
        ('inventory', '0021_reorderrequest_request_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='fitted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fitted_units', to='assets.assetcomponent'),
        ),
        migrations.RunPython(remember_where_the_issued_units_went, forget),
    ]
