# Generated by Django 5.1.15 on 2026-09-27 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_a_unit_says_where_it_went'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reorderrequest',
            name='declined_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reorderrequest',
            name='declined_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='declined_reorders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reorderrequest',
            name='declined_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
