# Generated by Django 5.1.15 on 2026-10-04 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_a_declined_reorder_says_why'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='inventoryunittype',
            options={'ordering': ['-created_at']},
        ),
    ]
