# Generated by Django 5.1.15 on 2026-10-05 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_inventoryitem_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsreceiptline',
            name='receiving_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='stocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='goodsreceiptline',
            name='stocked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stocked_receipt_lines', to=settings.AUTH_USER_MODEL),
        ),
    ]
