# Generated by Django 5.1.15 on 2026-10-07 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_inspection_carries_the_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='storage_location',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
