# Generated by Django 5.1.15 on 2026-10-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0028_units_say_where_they_are_kept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryunit',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('extended', 'Extended'), ('supplier', 'Supplier'), ('client', 'Customer Warranty')], max_length=20),
        ),
    ]
