# Generated by Django 5.1.15 on 2026-10-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_customer_warranty_is_its_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryunit',
            name='warranty_reference',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
