# Generated by Django 5.1.15 on 2026-10-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_parts_are_numbered_like_warranties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryunit',
            name='warranty_type',
            field=models.CharField(blank=True, choices=[('manufacturer', 'Manufacturer'), ('extended', 'Extended'), ('supplier', 'Supplier'), ('client', 'Client Warranty')], max_length=20),
        ),
    ]
