# Generated by Django 5.1.15 on 2026-07-08 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('in_process', 'In Process'), ('on_hold', 'On Hold'), ('overdue', 'Over Due'), ('completed', 'Completed')], default='active', max_length=15),
        ),
    ]
