# Generated by Django 5.1.15 on 2026-08-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_workflow'),
        ('suppliers', '0003_seed_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='vendors',
            field=models.ManyToManyField(blank=True, related_name='maintenance_schedules', to='suppliers.supplier'),
        ),
    ]
