# Generated by Django 5.1.15 on 2026-08-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_vendors_custom_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='required_components',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
