# Generated by Django 5.1.15 on 2026-08-31 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_required_components'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='charge_to',
            field=models.CharField(blank=True, choices=[('company', 'Company'), ('client', 'Client'), ('vendor', 'Vendor')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='is_billable',
            field=models.BooleanField(default=False),
        ),
    ]
