# Generated by Django 5.1.15 on 2026-09-21 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_reorderrequest_request_number'),
        ('maintenance', '0009_schedule_start_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePartRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('quantity_requested', models.PositiveIntegerField()),
                ('quantity_approved', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Withdrawn')], default='requested', max_length=12)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('decision_note', models.CharField(blank=True, max_length=300)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_parts_decided', to=settings.AUTH_USER_MODEL)),
                ('issuance_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_part_request', to='inventory.issuancerequest')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_part_requests', to='inventory.inventoryitem')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_parts_requested', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_requests', to='maintenance.maintenanceschedule')),
                ('unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_part_requests', to='inventory.inventoryunittype')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
