# Generated by Django 5.1.15 on 2026-09-21 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_technician_asks_supervisor_decides'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancepartrequest',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenancepartrequest',
            name='quantity_used',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancepartrequest',
            name='return_reference',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
