# Generated by Django 5.1.15 on 2026-09-22 17:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def open_a_round_for_every_live_schedule(apps, schema_editor):
    """Schedules written down before rounds existed still have one to plan.

    Their next due date and their standing technician become the open round,
    and anything already asked for on the job belongs to it — that is the
    round it was asked for.
    """
    Schedule = apps.get_model("maintenance", "MaintenanceSchedule")
    Visit = apps.get_model("maintenance", "MaintenanceVisit")
    for schedule in Schedule.objects.filter(is_active=True).exclude(status="completed"):
        visit = Visit.objects.create(
            schedule=schedule,
            due_date=schedule.next_due,
            assigned_to=schedule.assigned_to,
            status="in_progress" if schedule.status == "in_process" else "planned",
        )
        schedule.part_requests.filter(quantity_used__isnull=True).update(visit=visit)


def close_the_rounds(apps, schema_editor):
    apps.get_model("maintenance", "MaintenanceVisit").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_used_and_returned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceVisit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=12)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_visits', to=settings.AUTH_USER_MODEL)),
                ('record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit', to='maintenance.maintenancerecord')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='maintenance.maintenanceschedule')),
            ],
            options={
                'ordering': ['due_date', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='maintenancepartrequest',
            name='visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_requests', to='maintenance.maintenancevisit'),
        ),
        migrations.RunPython(open_a_round_for_every_live_schedule, close_the_rounds),
    ]
