# Generated by Django 5.1.15 on 2026-09-22 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_rounds_of_a_schedule'),
        ('tickets', '0017_predictive_not_preventive'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_jobs', to='tickets.ticket'),
        ),
    ]
