# Generated by Django 5.1.15 on 2026-09-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0016_every_asset_on_a_ticket_has_its_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending'), ('in_process', 'In Process'), ('on_hold', 'On Hold'), ('overdue', 'Over Due'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=15),
        ),
    ]
