# Generated by Django 5.1.15 on 2026-10-04 09:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_alter_maintenanceschedule_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancevisit',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='resolved',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='review_decision',
            field=models.CharField(blank=True, choices=[('accepted', 'Accepted as resolved'), ('unresolved', 'Marked unresolved')], default='', max_length=12),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='review_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='review_reason',
            field=models.CharField(blank=True, choices=[('parts_awaited', 'Parts awaited'), ('vendor_support', 'Vendor support needed'), ('site_access', 'Client/site access issue'), ('needs_replacement', 'Needs full replacement'), ('not_satisfactory', 'Work not satisfactory'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_visits_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='sequence',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='maintenancevisit',
            name='status',
            field=models.CharField(choices=[('planned', 'Planned'), ('in_progress', 'In Progress'), ('awaiting_review', 'Awaiting Review'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='planned', max_length=16),
        ),
        migrations.CreateModel(
            name='MaintenanceVisitPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('before', 'Before'), ('after', 'After'), ('other', 'Other')], default='other', max_length=8)),
                ('image', models.ImageField(upload_to='maintenance/visits/')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('taken_at', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('taken_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_visit_photos', to=settings.AUTH_USER_MODEL)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='maintenance.maintenancevisit')),
            ],
            options={
                'ordering': ['taken_at'],
            },
        ),
    ]
