# Generated by Django 5.1.15 on 2026-10-04 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_alter_maintenancevisit_review_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancevisit',
            name='start_latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='maintenancevisit',
            name='start_longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
