# Generated by Django 5.1.15 on 2026-10-04 16:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0021_maintenancevisit_start_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceCostLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('component', 'Component used'), ('manual', 'Added on review')], default='manual', max_length=12)),
                ('description', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='maintenance.maintenancerecord')),
            ],
            options={
                'ordering': ['source', 'created_at'],
            },
        ),
    ]
