# Generated by Django 5.1.15 on 2026-04-23 17:58

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='state_province',
            field=models.CharField(blank=True, help_text='State, province, or emirate', max_length=150),
        ),
        migrations.AlterField(
            model_name='site',
            name='country',
            field=models.CharField(default='Pakistan', max_length=100),
        ),
        migrations.CreateModel(
            name='InstallationStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_type', models.CharField(choices=[('survey', 'Survey'), ('wiring', 'Wiring'), ('structure', 'Metal Structure Installation'), ('programming', 'Programming'), ('testing', 'Testing & Commissioning'), ('handover', 'Handover')], max_length=20)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started Yet'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('assigned_team', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sites.deviceinstallation')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('installation', 'step_number')},
            },
        ),
    ]
