# Generated by Django 5.1.15 on 2026-08-20 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_sitecontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstallation',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='Auto-stamped when every step is completed or skipped', null=True),
        ),
        migrations.AddField(
            model_name='deviceinstallation',
            name='due_date',
            field=models.DateField(blank=True, help_text='Agreed completion date for the installation', null=True),
        ),
        migrations.CreateModel(
            name='InstallationDelay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cause', models.CharField(choices=[('client', 'Client'), ('internal', 'Internal'), ('vendor', 'Vendor'), ('other', 'Other')], max_length=15)),
                ('description', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='sites.deviceinstallation')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_delays_reported', to=settings.AUTH_USER_MODEL)),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delays', to='sites.installationstep')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
