# Generated by Django 5.1.15 on 2026-08-25 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_deviceinstallation_completed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationstep',
            name='status',
            field=models.CharField(choices=[('not_started', 'Not Started Yet'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold (Client)'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20),
        ),
    ]
