# Generated by Django 5.1.15 on 2026-08-25 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_step_on_hold'),
        ('suppliers', '0003_seed_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstallation',
            name='vendor',
            field=models.ForeignKey(blank=True, help_text='External vendor doing the installation work', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installations', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='installationstep',
            name='custom_label',
            field=models.CharField(blank=True, help_text="Display name for custom ('other') steps", max_length=200),
        ),
        migrations.AlterField(
            model_name='installationstep',
            name='step_type',
            field=models.CharField(choices=[('survey', 'Survey'), ('wiring', 'Wiring'), ('structure', 'Metal Structure Installation'), ('programming', 'Programming'), ('testing', 'Testing & Commissioning'), ('handover', 'Handover'), ('other', 'Other')], max_length=20),
        ),
    ]
