# Generated by Django 5.1.15 on 2026-08-31 13:20

import common.utils
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_device_source_alter_device_status'),
        ('clients', '0002_alter_client_code'),
        ('sites', '0006_vendors_custom_steps'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='installationphoto',
            name='photo_type',
            field=models.CharField(choices=[('pre_install', 'Pre-Installation'), ('post_install', 'Post-Installation'), ('verification', 'Verification'), ('handover', 'Handover')], max_length=20),
        ),
        migrations.CreateModel(
            name='HandoverRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('handover_date', models.DateField()),
                ('accepted_by_name', models.CharField(max_length=200)),
                ('acceptance_notes', models.TextField(blank=True)),
                ('signature', models.ImageField(blank=True, upload_to=common.utils.upload_to_path)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='clients.client')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='assets.device')),
                ('installation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover', to='sites.deviceinstallation')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_performed', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handovers', to='sites.site')),
            ],
            options={
                'ordering': ['-handover_date'],
            },
        ),
    ]
