# Generated by Django 5.1.15 on 2026-08-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0007_alter_installationphoto_photo_type_handoverrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstallation',
            name='escalation_state',
            field=models.JSONField(blank=True, default=dict, help_text='Escalation ledger: "<trigger>:<stage>" -> ISO timestamp when that stage fired.'),
        ),
    ]
