# Generated by Django 5.1.15 on 2026-09-02 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0008_deviceinstallation_escalation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinstallation',
            name='external_vendor_contact',
            field=models.CharField(blank=True, help_text='Phone or contact person for the manual vendor', max_length=100),
        ),
        migrations.AddField(
            model_name='deviceinstallation',
            name='external_vendor_name',
            field=models.CharField(blank=True, help_text='Vendor named by hand when they are not a registered supplier', max_length=200),
        ),
    ]
