# Generated by Django 5.1.15 on 2026-09-10 19:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_device_supply_vendor_contact_and_more'),
        ('sites', '0009_deviceinstallation_external_vendor_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationRouteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('asset_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='installation_template', to='assets.assettype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installation_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_type__name'],
            },
        ),
        migrations.CreateModel(
            name='InstallationRouteTemplateStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('step_type', models.CharField(choices=[('survey', 'Survey'), ('wiring', 'Wiring'), ('structure', 'Metal Structure Installation'), ('programming', 'Programming'), ('testing', 'Testing & Commissioning'), ('handover', 'Handover'), ('other', 'Other')], max_length=20)),
                ('custom_label', models.CharField(blank=True, max_length=200)),
                ('assigned_team', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='sites.installationroutetemplate')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('template', 'step_number')},
            },
        ),
    ]
