# Generated by Django 5.1.15 on 2026-09-20 15:01

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0011_backfill_installation_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='handoverrecord',
            name='signed_document',
            field=models.FileField(blank=True, help_text='The handover document, signed by the client.', upload_to=common.utils.upload_to_path),
        ),
    ]
