# Generated by Django 5.1.15 on 2026-10-04 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0013_installationstep_completed_by'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='site',
            options={'ordering': ['-created_at']},
        ),
    ]
