# Generated by Django 5.1.15 on 2026-04-21 23:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_initial'),
        ('suppliers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warranty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('warranty_type', models.CharField(choices=[('manufacturer', 'Manufacturer'), ('extended', 'Extended'), ('supplier', 'Supplier')], default='manufacturer', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('claimed', 'Claimed'), ('void', 'Void')], default='active', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('coverage_details', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='warranties', to='assets.device')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='suppliers.supplier')),
            ],
            options={
                'verbose_name_plural': 'warranties',
                'ordering': ['-end_date'],
            },
        ),
    ]
