# Generated by Django 5.1.15 on 2026-08-17 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='months',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Term in months (client warranties: 3/6/12)', null=True),
        ),
        migrations.AddField(
            model_name='warranty',
            name='reissued_from',
            field=models.ForeignKey(blank=True, help_text='Original warranty this one was reissued from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reissues', to='warranties.warranty'),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Warranty Completed'), ('reissued', 'Reissued'), ('claimed', 'Claimed'), ('void', 'Void')], default='active', max_length=10),
        ),
        migrations.AlterField(
            model_name='warranty',
            name='warranty_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('extended', 'Extended'), ('supplier', 'Supplier'), ('client', 'Client Warranty')], default='manufacturer', max_length=20),
        ),
    ]
