# Generated by Django 5.1.15 on 2026-08-25 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_components_suppliers_warranties'),
        ('warranties', '0002_warranty_months_warranty_reissued_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warranty',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranties', to='assets.assetcomponent'),
        ),
    ]
