# Generated by Django 5.1.15 on 2026-08-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0003_components_suppliers_warranties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Warranty Completed'), ('reissued', 'Reissued'), ('claimed', 'Pending'), ('void', 'Void')], default='active', max_length=10),
        ),
    ]
