# Generated by Django 5.1.15 on 2026-09-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0004_vendors_custom_steps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='warranty_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('extended', 'Extended'), ('supplier', 'Vendor'), ('client', 'Client Warranty')], default='manufacturer', max_length=20),
        ),
    ]
