# Generated by Django 5.1.15 on 2026-10-07 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0007_component_cover_is_the_suppliers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='warranty_type',
            field=models.CharField(choices=[('manufacturer', 'Manufacturer'), ('extended', 'Extended'), ('supplier', 'Vendor'), ('client', 'Customer Warranty')], default='manufacturer', max_length=20),
        ),
    ]
