# Generated by Django 5.1.15 on 2026-10-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0010_client_warranty_is_its_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warranty',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('reissued', 'Reissued'), ('claimed', 'Pending'), ('void', 'Void')], default='active', max_length=10),
        ),
    ]
