# Generated by Django 5.1.15 on 2026-10-07 20:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0032_alter_device_status'),
        ('inventory', '0032_client_warranty_is_its_name'),
        ('suppliers', '0004_alter_supplier_options'),
        ('warranties', '0011_expired_reads_expired'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claim_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('fault', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('failure_date', models.DateField()),
                ('expected_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('evidence', models.FileField(blank=True, upload_to='warranty_claims/')),
                ('status', models.CharField(choices=[('raised', 'Raised'), ('submitted', 'Sent to Vendor'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('closed', 'Closed'), ('withdrawn', 'Withdrawn')], default='raised', max_length=12)),
                ('vendor_reference', models.CharField(blank=True, max_length=200)),
                ('resolution', models.CharField(blank=True, choices=[('repaired', 'Repaired'), ('replaced', 'Replaced'), ('credit_note', 'Credit Note'), ('refund', 'Refund')], max_length=12)),
                ('recovered_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('history', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to='assets.device')),
                ('inventory_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='inventory.inventoryunit')),
                ('raised_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claims', to='suppliers.supplier')),
                ('warranty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='warranties.warranty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
