# Generated by Django 5.1.15 on 2026-04-21 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0001_initial'),
        ('sites', '0001_initial'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='current_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='sites.site'),
        ),
        migrations.AddField(
            model_name='device',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='suppliers.supplier'),
        ),
        migrations.AddField(
            model_name='assetcode',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_labels', to='assets.device'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lifecycle_events', to='assets.device'),
        ),
        migrations.AddField(
            model_name='devicelifecycleevent',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='device_models', to='assets.brand'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='assets.devicemodel'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemodel',
            unique_together={('brand', 'name')},
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['status'], name='assets_devi_status_03b2ce_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['serial_number'], name='assets_devi_serial__79b06b_idx'),
        ),
        migrations.AddIndex(
            model_name='device',
            index=models.Index(fields=['asset_code'], name='assets_devi_asset_c_08af6c_idx'),
        ),
    ]
