# Generated by Django 5.1.15 on 2026-07-06 22:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_device_image_deviceimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('code', models.CharField(blank=True, db_index=True, max_length=30)),
                ('description', models.TextField(blank=True)),
                ('has_dimensions', models.BooleanField(default=False, help_text='Uses length × width (e.g. SMD screens)')),
                ('has_diagonal', models.BooleanField(default=False, help_text='Uses diagonal size in inches (e.g. digital displays)')),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='device',
            name='diagonal_inches',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='display_name',
            field=models.CharField(blank=True, help_text='Friendly asset name', max_length=200),
        ),
        migrations.AddField(
            model_name='device',
            name='installed_by',
            field=models.ForeignKey(blank=True, help_text='Who installed this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installed_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='device',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='width_cm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='asset_type',
            field=models.ForeignKey(blank=True, help_text='Asset category (SMD Screen, Standee, Digital Display, …)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='assets.assettype'),
        ),
    ]
