# Generated by Django 5.1.15 on 2026-08-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_seed_asset_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('procured', 'Procured'), ('in_stock', 'In Stock'), ('assigned', 'Assigned to Client'), ('installed', 'Installed'), ('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('client_property', 'Client Property'), ('decommissioned', 'Decommissioned'), ('lost_stolen', 'Lost/Stolen'), ('rma', 'RMA'), ('in_transit', 'In Transit')], default='procured', max_length=20),
        ),
    ]
