# Generated by Django 5.1.15 on 2026-08-17 07:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_alter_device_status'),
        ('teams', '0002_project_source_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='teams.project'),
        ),
        migrations.CreateModel(
            name='AssetComponent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='e.g. SMD Cabinet P3.9', max_length=200)),
                ('component_type', models.CharField(blank=True, help_text='e.g. Cabinet, Media Player, PSU', max_length=100)),
                ('serial_number', models.CharField(blank=True, max_length=200)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assets.device')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
