# Generated by Django 5.1.15 on 2026-08-20 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0007_device_project_assetcomponent'),
        ('clients', '0002_alter_client_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='clients',
            field=models.ManyToManyField(blank=True, related_name='shared_devices', to='clients.client'),
        ),
    ]
