# Generated by Django 5.1.15 on 2026-08-25 05:52
from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models

CM_PER_INCH = Decimal("2.54")


def cm_to_inches(apps, schema_editor):
    Device = apps.get_model("assets", "Device")
    for device in Device.objects.exclude(length_in=None, width_in=None):
        if device.length_in is not None:
            device.length_in = round(device.length_in / CM_PER_INCH, 2)
        if device.width_in is not None:
            device.width_in = round(device.width_in / CM_PER_INCH, 2)
        device.save(update_fields=["length_in", "width_in"])


def inches_to_cm(apps, schema_editor):
    Device = apps.get_model("assets", "Device")
    for device in Device.objects.exclude(length_in=None, width_in=None):
        if device.length_in is not None:
            device.length_in = round(device.length_in * CM_PER_INCH, 2)
        if device.width_in is not None:
            device.width_in = round(device.width_in * CM_PER_INCH, 2)
        device.save(update_fields=["length_in", "width_in"])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_device_clients'),
        ('suppliers', '0003_seed_service_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='length_cm',
            new_name='length_in',
        ),
        migrations.RenameField(
            model_name='device',
            old_name='width_cm',
            new_name='width_in',
        ),
        migrations.AddField(
            model_name='device',
            name='depth_in',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        # Existing values were stored in centimetres; convert them in place.
        migrations.RunPython(cm_to_inches, inches_to_cm),
        migrations.AddField(
            model_name='assetcomponent',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplied_components', to='suppliers.supplier'),
        ),
    ]
