# Generated by Django 5.1.15 on 2026-08-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_components_suppliers_warranties'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='source',
            field=models.CharField(choices=[('inhouse', 'In-house Production'), ('third_party', 'Third Party')], db_index=True, default='third_party', max_length=20),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('procured', 'Procured'), ('in_production', 'In Production'), ('in_stock', 'In Stock'), ('assigned', 'Assigned to Client'), ('installed', 'Installed'), ('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('client_property', 'Client Property'), ('decommissioned', 'Decommissioned'), ('lost_stolen', 'Lost/Stolen'), ('rma', 'RMA'), ('in_transit', 'In Transit')], default='procured', max_length=20),
        ),
    ]
