# Generated by Django 5.1.15 on 2026-09-01 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0010_device_source_alter_device_status'),
        ('inventory', '0006_inventoryunit'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='inventory_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_components', to='inventory.inventoryitem'),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='inventory_unit',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_component', to='inventory.inventoryunit'),
        ),
    ]
