# Generated by Django 5.1.15 on 2026-09-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0011_assetcomponent_inventory_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_vendor_contact',
            field=models.CharField(blank=True, help_text='Phone or contact person for the assigned vendor', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='assigned_vendor_name',
            field=models.CharField(blank=True, help_text='External vendor this asset is assigned to', max_length=200),
        ),
    ]
