# Generated by Django 5.1.15 on 2026-09-04 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0012_device_assigned_vendor_contact_and_more'),
        ('inventory', '0009_inventoryunittype_inventoryunit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='inventory_unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_components', to='inventory.inventoryunittype'),
        ),
    ]
