# Generated by Django 5.1.15 on 2026-09-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0013_assetcomponent_inventory_unit_type'),
        ('procurement', '0005_purchaseorderitem_bom_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='fulfilment',
            field=models.CharField(choices=[('pending', 'Not Decided'), ('from_stock', 'From Inventory'), ('procurement', 'To Be Procured'), ('fulfilled', 'Fulfilled')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='issued_quantity',
            field=models.PositiveIntegerField(default=0, help_text='How much of the requirement has actually left the warehouse'),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='purchase_order_item',
            field=models.ForeignKey(blank=True, help_text='PO line raised to cover this requirement', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_components', to='procurement.purchaseorderitem'),
        ),
    ]
