# Generated by Django 5.1.15 on 2026-09-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0014_assetcomponent_fulfilment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, unique=True),
        ),
    ]
