# Generated by Django 5.1.15 on 2026-09-10 10:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0015_alter_device_serial_number'),
        ('suppliers', '0003_seed_service_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='device_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='assets.devicemodel'),
        ),
        migrations.AlterField(
            model_name='device',
            name='source',
            field=models.CharField(choices=[('inhouse', 'In-house Production'), ('vendor_supplied', 'Vendor Supplied · Installed In-house'), ('vendor_turnkey', 'Vendor Supplied & Installed')], db_index=True, default='inhouse', max_length=20),
        ),
        migrations.CreateModel(
            name='ProductionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(help_text='e.g. Frame welding, Panaflex pasting', max_length=200)),
                ('location', models.CharField(choices=[('in_house', 'In-house'), ('external', 'Outside Workshop')], default='in_house', max_length=12)),
                ('workshop_name', models.CharField(blank=True, help_text='Workshop named by hand when it is not a registered supplier', max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('sent_out', 'Sent to Workshop'), ('returned', 'Returned from Workshop'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12)),
                ('expected_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_steps', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_steps', to='assets.device')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_steps', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['step_number', 'created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='assets_prod_device__770fef_idx')],
                'unique_together': {('device', 'step_number')},
            },
        ),
    ]
