# Generated by Django 5.1.15 on 2026-09-10 11:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0017_map_third_party_source'),
        ('suppliers', '0003_seed_service_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionRouteTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('asset_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='route_template', to='assets.assettype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ProductionRouteTemplateStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(default='in_house', max_length=12)),
                ('workshop_name', models.CharField(blank=True, max_length=200)),
                ('expected_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='assets.productionroutetemplate')),
                ('workshop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='route_template_steps', to='suppliers.supplier')),
            ],
            options={
                'ordering': ['step_number'],
                'unique_together': {('template', 'step_number')},
            },
        ),
    ]
