# Generated by Django 5.1.15 on 2026-09-10 12:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0018_productionroutetemplate_productionroutetemplatestep'),
        ('inventory', '0009_inventoryunittype_inventoryunit_unit_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('asset_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='component_template', to='assets.assettype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['asset_type__name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentTemplateLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('inventory_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_template_lines', to='inventory.inventoryitem')),
                ('inventory_unit_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='component_template_lines', to='inventory.inventoryunittype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='assets.componenttemplate')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
