# Generated by Django 5.1.15 on 2026-09-10 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0019_componenttemplate_componenttemplateline'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='supply_vendor_contact',
            field=models.CharField(blank=True, help_text='Phone or contact person for the supplying vendor', max_length=100),
        ),
        migrations.AddField(
            model_name='device',
            name='supply_vendor_name',
            field=models.CharField(blank=True, help_text='Vendor the finished asset was bought from', max_length=200),
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_vendor_contact',
            field=models.CharField(blank=True, help_text='Phone or contact person for the installing vendor', max_length=100),
        ),
        migrations.AlterField(
            model_name='device',
            name='assigned_vendor_name',
            field=models.CharField(blank=True, help_text='External vendor installing this asset', max_length=200),
        ),
    ]
