# Generated by Django 5.1.15 on 2026-09-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0020_device_supply_vendor_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='planned_unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='planned_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
