# Generated by Django 5.1.15 on 2026-09-13 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0021_assetcomponent_planned_unit_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcomponent',
            name='increase_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='increase_reason',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='increase_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='increase_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='component_increase_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='pending_increase',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
