# Generated by Django 5.1.15 on 2026-09-16 21:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def link_categories(apps, schema_editor):
    """Every typed category becomes (or joins) an inventory category."""
    MaterialType = apps.get_model("assets", "MaterialType")
    InventoryCategory = apps.get_model("inventory", "InventoryCategory")

    for component in MaterialType.objects.exclude(legacy_category=""):
        name = component.legacy_category.strip()
        if not name:
            continue
        category = InventoryCategory.objects.filter(name__iexact=name).first()
        if category is None:
            category = InventoryCategory.objects.create(name=name)
        component.category = category
        component.save(update_fields=["category"])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0022_assetcomponent_increase_notes_and_more'),
        ('inventory', '0013_goodsreceipt_source_inventoryitem_watch_on_dashboard_and_more'),
        ('procurement', '0008_purchaseorder_terms'),
        ('suppliers', '0003_seed_service_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialtype',
            options={'ordering': ['name'], 'verbose_name': 'component'},
        ),
        migrations.AddField(
            model_name='assetcomponent',
            name='unit',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='procurement_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procured_devices', to='procurement.purchaseorderitem'),
        ),
        migrations.AddField(
            model_name='productionstep',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('procured', 'In Procurement'), ('in_production', 'In Production'), ('in_stock', 'In Stock'), ('assigned', 'Assigned to Client'), ('installed', 'Installed'), ('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('client_property', 'Client Property'), ('decommissioned', 'Decommissioned'), ('lost_stolen', 'Lost/Stolen'), ('rma', 'RMA'), ('in_transit', 'In Transit')], default='procured', max_length=20),
        ),
        # The free-text category becomes a link to the inventory categories.
        # Rename keeps every existing value; the FK is then filled from it.
        migrations.RenameField(
            model_name='materialtype',
            old_name='category',
            new_name='legacy_category',
        ),
        migrations.AlterField(
            model_name='materialtype',
            name='legacy_category',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AddField(
            model_name='materialtype',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='components', to='inventory.inventorycategory'),
        ),
        migrations.RunPython(link_categories, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='assetcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_item__isnull', False)), fields=('device', 'inventory_item'), name='uniq_component_generic_per_device'),
        ),
        migrations.AddConstraint(
            model_name='assetcomponent',
            constraint=models.UniqueConstraint(condition=models.Q(('inventory_unit_type__isnull', False)), fields=('device', 'inventory_unit_type'), name='uniq_component_unique_per_device'),
        ),
    ]
