# Generated by Django 5.1.15 on 2026-09-17 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_materialtype_options_assetcomponent_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='procurement_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
