# Generated by Django 5.1.15 on 2026-09-17 18:44

from django.db import migrations, models


def hand_decisions_to_projects(apps, schema_editor):
    """Where an operation happens is now decided in the project's Execution tab.
    Steps on a project that were merely defaulted to in-house become undecided;
    steps with a workshop keep it; steps on assets outside any project stay in-house."""
    ProductionStep = apps.get_model("assets", "ProductionStep")
    ProjectScopeItem = apps.get_model("teams", "ProjectScopeItem")
    scoped = set(ProjectScopeItem.objects.values_list("device_id", flat=True))
    for step in ProductionStep.objects.select_related("device").filter(location="in_house", workshop__isnull=True, workshop_name=""):
        if step.device.project_id or step.device_id in scoped:
            step.location = "undecided"
            step.save(update_fields=["location"])



class Migration(migrations.Migration):

    dependencies = [
        ("teams", "0011_project_sites_alter_project_phase_and_more"),
        ('assets', '0024_vendor_asset_procurement_and_step_work_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionstep',
            name='location',
            field=models.CharField(choices=[('undecided', 'Not decided'), ('in_house', 'In-house'), ('external', 'Outside Workshop')], default='undecided', max_length=12),
        ),
        migrations.AlterField(
            model_name='productionstep',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('sent_out', 'Work Order Raised'), ('returned', 'Returned from Workshop'), ('completed', 'Completed'), ('skipped', 'Skipped')], db_index=True, default='pending', max_length=12),
        ),
        migrations.RunPython(hand_decisions_to_projects, migrations.RunPython.noop),
    ]
