# Generated by Django 5.1.15 on 2026-09-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0026_reopen_copied_route_decisions'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstep',
            name='work_order_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
