# Generated by Django 5.1.15 on 2026-09-20 08:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0027_productionstep_work_order_requested_at'),
        ('suppliers', '0003_seed_service_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='assigned_vendor',
            field=models.ForeignKey(blank=True, help_text='Vendor installing this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='installing_devices', to='suppliers.supplier'),
        ),
    ]
