# Generated by Django 5.1.15 on 2026-09-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0028_device_assigned_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='actual_installation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What installing and activating this asset actually cost', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='planned_installation_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='What installing and activating this asset is expected to cost', max_digits=12, null=True),
        ),
    ]
