# Generated by Django 5.1.15 on 2026-09-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0030_asset_code_identifies_the_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='dimension_unit',
            field=models.CharField(choices=[('in', 'Inches (in)'), ('cm', 'Centimetres (cm)'), ('mm', 'Millimetres (mm)'), ('ft', 'Feet (ft)'), ('m', 'Metres (m)')], default='in', max_length=2),
        ),
    ]
