# Generated by Django 5.1.15 on 2026-10-04 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0031_dimensions_carry_their_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(choices=[('procured', 'In Procurement'), ('in_production', 'In Production'), ('in_stock', 'In Stock'), ('assigned', 'Assigned for Installation'), ('installed', 'Installed'), ('active', 'Active'), ('under_maintenance', 'Under Maintenance'), ('client_property', 'Client Property'), ('decommissioned', 'Decommissioned'), ('lost_stolen', 'Lost/Stolen'), ('rma', 'RMA'), ('in_transit', 'In Transit')], default='procured', max_length=20),
        ),
    ]
