# Generated by Django 5.1.15 on 2026-07-06 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
    ]
