# Generated by Django 5.1.15 on 2026-07-07 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_work_order',
            field=models.ForeignKey(blank=True, help_text='Work order this project was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='workorders.workorder'),
        ),
    ]
