# Generated by Django 5.1.15 on 2026-08-25 06:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0009_components_suppliers_warranties'),
        ('sites', '0005_step_on_hold'),
        ('teams', '0002_project_source_work_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('query', 'Query'), ('on_hold', 'On Hold'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('order_confirmation', 'Order Confirmation'), ('lost', 'Lost'), ('production', 'Production'), ('delivery', 'Delivery'), ('installation', 'Installation'), ('handover', 'Handing Over'), ('under_warranty', 'Under Warranty'), ('extended_warranty', 'Extended Warranty'), ('decommissioned', 'De-Commissioned')], default='query', max_length=25),
        ),
        migrations.CreateModel(
            name='ProjectMilestone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='teams.project')),
            ],
            options={
                'ordering': ['order', 'due_date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectScopeItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scope_items', to='assets.assetcomponent')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_scope_items', to='assets.device')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scope_items', to='teams.project')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_scope_items', to='sites.site')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
