# Generated by Django 5.1.15 on 2026-08-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_project_phase_scope_milestones'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('sold', 'Sold Outright'), ('rental', 'Rental')], default='', help_text='Whether the project is sold outright or rented', max_length=10),
        ),
        migrations.AddField(
            model_name='project',
            name='rental_end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
