# Generated by Django 5.1.15 on 2026-08-31 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotations', '0001_initial'),
        ('teams', '0005_projectbomline_bomallocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source_quotation',
            field=models.ForeignKey(blank=True, help_text='Quotation this project was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='spawned_projects', to='quotations.quotation'),
        ),
        migrations.AddField(
            model_name='projectbomline',
            name='source_quotation_item',
            field=models.ForeignKey(blank=True, help_text='Quotation line this BOM line was copied from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_lines', to='quotations.quotationitem'),
        ),
    ]
