# Generated by Django 5.1.15 on 2026-09-01 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_goodsreceiptline_accepted_quantity_and_more'),
        ('teams', '0006_project_source_quotation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bomallocation',
            name='inventory_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bom_allocations', to='inventory.inventoryunit'),
        ),
    ]
