# Generated by Django 5.1.15 on 2026-09-12 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_scope_rows_for_project_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectcostline',
            name='actual_quantity',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='projectcostline',
            name='actual_unit_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
