# Generated by Django 5.1.15 on 2026-09-16 21:18

from django.db import migrations, models


def retire_asset_phases(apps, schema_editor):
    """The phases after handover belong to the asset's life, not the order's.

    Anything sitting in one of them has been handed over, so that is where it
    goes; the asset itself carries warranty and decommissioning.
    """
    Project = apps.get_model("teams", "Project")
    Project.objects.filter(
        phase__in=["under_warranty", "extended_warranty", "decommissioned"]
    ).update(phase="handover")


def one_row_per_asset(apps, schema_editor):
    """Keep the first scope row for each (project, asset); drop the rest."""
    ProjectScopeItem = apps.get_model("teams", "ProjectScopeItem")
    seen = set()
    for row in ProjectScopeItem.objects.order_by("created_at", "id"):
        key = (row.project_id, row.device_id)
        if key in seen:
            row.delete()
        else:
            seen.add(key)


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0023_alter_materialtype_options_assetcomponent_unit_and_more'),
        ('sites', '0011_backfill_installation_dates'),
        ('teams', '0010_projectcostline_actual_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='sites',
            field=models.ManyToManyField(blank=True, related_name='scoped_projects', to='sites.site'),
        ),
        migrations.RunPython(retire_asset_phases, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('query', 'Query'), ('on_hold', 'On Hold'), ('quotation', 'Quotation'), ('negotiation', 'Negotiation'), ('order_confirmation', 'Order Confirmation'), ('lost', 'Order Lost'), ('production', 'Production'), ('delivery', 'Delivery'), ('installation', 'Installation'), ('handover', 'Handing Over')], default='query', max_length=25),
        ),
        migrations.AlterField(
            model_name='projectcostline',
            name='cost_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.RunPython(one_row_per_asset, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='projectscopeitem',
            constraint=models.UniqueConstraint(fields=('project', 'device'), name='uniq_asset_per_project'),
        ),
    ]
