# Generated by Django 5.1.15 on 2026-09-20 11:53

from django.db import migrations, models


# The commercial run-up is one phase to the delivery team; delivery and
# installation are the same trip to site.
OLD_TO_NEW = {
    "query": "planning",
    "quotation": "planning",
    "negotiation": "planning",
    "order_confirmation": "planning",
    "delivery": "installation",
}


def move_projects_onto_the_new_phases(apps, schema_editor):
    Project = apps.get_model("teams", "Project")
    for old, new in OLD_TO_NEW.items():
        Project.objects.filter(phase=old).update(phase=new)


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0011_project_sites_alter_project_phase_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='phase',
            field=models.CharField(choices=[('planning', 'Planning'), ('procurement', 'Procurement'), ('production', 'Production'), ('installation', 'Installation'), ('handover', 'Handing Over'), ('on_hold', 'On Hold'), ('lost', 'Order Lost')], default='planning', max_length=25),
        ),
        migrations.RunPython(move_projects_onto_the_new_phases, migrations.RunPython.noop),
    ]
