# Generated by Django 5.1.15 on 2026-10-07 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0012_project_phases_follow_the_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client_warranty_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
