# Generated by Django 5.1.15 on 2026-04-23 20:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('notifications', '0001_initial'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_actionable',
            field=models.BooleanField(default=False, help_text='Actionable notifications stay visible until their linked entity is resolved.'),
        ),
        migrations.AddField(
            model_name='notification',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='tickets.ticket'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('chat_message', 'Chat Message'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_update', 'Ticket Update'), ('maintenance_reminder', 'Maintenance Reminder'), ('system', 'System')], default='system', max_length=30),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['ticket', 'notification_type'], name='notificatio_ticket__8b2190_idx'),
        ),
    ]
