# Generated by Django 5.1.15 on 2026-08-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('chat_message', 'Chat Message'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_update', 'Ticket Update'), ('ticket_review', 'Ticket Review Request'), ('ticket_escalated', 'Ticket Escalated'), ('installation_assigned', 'Installation Assigned'), ('maintenance_reminder', 'Maintenance Reminder'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
