# Generated by Django 5.1.15 on 2026-08-31 14:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_alter_notification_notification_type'),
        ('sites', '0008_deviceinstallation_escalation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='installation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='sites.deviceinstallation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('chat_message', 'Chat Message'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_update', 'Ticket Update'), ('ticket_review', 'Ticket Review Request'), ('ticket_escalated', 'Ticket Escalated'), ('installation_assigned', 'Installation Assigned'), ('installation_escalated', 'Installation Escalated'), ('maintenance_reminder', 'Maintenance Reminder'), ('system', 'System')], default='system', max_length=30),
        ),
    ]
