# Generated by Django 5.1.15 on 2026-10-07 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_stickynote'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='link',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='notification',
            name='ref',
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('alert', 'Alert'), ('chat_message', 'Chat Message'), ('ticket_assigned', 'Ticket Assigned'), ('ticket_update', 'Ticket Update'), ('ticket_review', 'Ticket Review Request'), ('ticket_escalated', 'Ticket Escalated'), ('installation_assigned', 'Installation Assigned'), ('installation_escalated', 'Installation Escalated'), ('maintenance_reminder', 'Maintenance Reminder'), ('system', 'System'), ('approval_requested', 'Approval Requested'), ('approval_decided', 'Approval Decided'), ('request_raised', 'Request Raised'), ('request_answered', 'Request Answered'), ('work_assigned', 'Work Assigned'), ('workflow_update', 'Workflow Update'), ('digest', 'Daily Summary')], default='system', max_length=30),
        ),
    ]
